4.4	Mảng nhiều chiều:
4.4.1 Tạo mảng nhiều chiều:
o	Từ object có định dạng array: sử dụng array()


In [4]:
import numpy as np
# Tao mang
array_2 = np.array([[1, 2, 3],[4, 5, 6]])
print(array_2)

print(array_2[::-1,:])



[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]


o	Có giá trị mặc định là 0, 1: dùng zeros(), ones()

In [6]:
mang_zeros = np.zeros([2, 2, 2], dtype = int)
print("Mang 0")
print(mang_zeros)

mang_ones = np.ones([2, 2], dtype = int)
print(mang_ones)

Mang 0
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[1 1]
 [1 1]]


4.4.2 Thao tác trên mảng nhiều chiều:
o	Số dòng, cột trên mảng
 
o	Cập nhật phần tử trong mảng
 
o	Truy xuất phần tử trên mảng: theo ma trận, dòng, cột (index = 0 -> chiều dài - 1)


In [7]:
# truy xuat phan tu trong mang
print(array_2)
print(array_2[1,2])
print(array_2[1,])


[[1 2 3]
 [4 5 6]]
6
[4 5 6]


o	Thay đổi kích cỡ mảng: dùng shape, reshape(số_lượng_ma_trận, số_dòng, số_cột)

In [12]:
print(array_2)
print(array_2.shape)
array_2.shape = (3,2)
print(array_2)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [14]:
# thay doi kich co mang dung reshape
a = np.arange(24)
print(a)

b = a.reshape(2, 3, 4) # ma tran, dong ,cot
print(b)
print(b[0][1][2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
6


o	Tìm max, min: sử dụng amax(), amin()

In [22]:
a = np.array([[3, 7, 2],
              [4, 5, 9],
              [8, 3, 6]])
print(a)
print("Max:", np.amax(a))
print("Min:", np.amin(a))
print("Max - theo tung cot", np.amax(a, 0))
print("Max - theo tung cot", np.amin(a, 0))
print("Max - theo tung dong", np.amax(a, 1))
print("Max - theo tung dong", np.amin(a, 1))


[[3 7 2]
 [4 5 9]
 [8 3 6]]
Max: 9
Min: 2
Max - theo tung cot [8 7 9]
Max - theo tung cot [3 3 2]
Max - theo tung dong [7 9 8]
Max - theo tung dong [2 4 3]


o	Giá trị trung bình số học: sử dụng mean()

In [23]:
b = np.array([  [ [3, 7], [8, 4] ], [ [2, 4], [1, 5] ]  ])
print(b)
print("Mean b:")
print(np.mean(b))
print("Mean b[0]:")
print(np.mean(b[0]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Mean b:
4.25
Mean b[0]:
5.5


In [24]:
print(b)
print("Median b:")
print(np.median(b))
print("Median b[1]:")
print(np.median(b[1]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Median b:
4.0
Median b[1]:
3.0


In [25]:
c = np.array([ [ [9,7],[8,4] ], [ [2,4], [6,5] ] ])
print(c)
print("Sort c")
print(np.sort(c))


[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Sort c
[[[7 9]
  [4 8]]

 [[2 4]
  [5 6]]]


In [27]:
print("Sort c[0] axis 1 ( theo dong ):")
print(np.sort(c[0], axis = 1))

Sort c[0] axis 1 ( theo dong ):
[[7 9]
 [4 8]]


In [28]:
print("Sort c[0] axis 0 ( theo cot ):")
print(np.sort(c[0], axis = 0))

Sort c[0] axis 0 ( theo cot ):
[[8 4]
 [9 7]]


o	Tìm index của các phần tử trong mảng thỏa điều kiện: sử dụng where()

In [ ]:
print(c)
cond = np.where(c > 5)
print(cond)
print(c[cond])
# (array([0, 0, 0, 1]), array([0, 0, 1, 1]), array([0, 1, 0, 0]))
#  array([ khoi , dong , cot, ])
# [9 7 8 6]

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
(array([0, 0, 0, 1]), array([0, 0, 1, 1]), array([0, 1, 0, 0]))
[9 7 8 6]


In [30]:
print(c)
print("Tren c:", np.extract( c >= 5,c ))
print("Tren c[0]:", np.extract( c[0] >= 5, c[0] ))

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Tren c: [9 7 8 6 5]
Tren c[0]: [9 7 8]
