NUMPY
4.1Giới thiệu:
-Là một thư viện bao gồm các đối tượng mảng đa chiều (multidimensional array) và một tập hợp các phương thức để xử lý mảng đa chiều đó.
-Sử dụng Numpy, các toán tử toán học và logic có thể được thực hiện
-Thay thế cho List
-Cài đặt: pip install numpy
4.2Ưu điểm :
-Chứa bộ các giá trị
-Có thể chứa các loại dữ liệu khác nhau
-Có thể thay đổi, thêm, xóa
-Đầy đủ chức năng tính toán
-Rất nhiều thư viện được xây dựng sẵn trong Numpy


In [1]:
#Tạo mảng một chiều trong numpy
import numpy as np
array_1 = np.array([1, 2, 3])
print(array_1)
print(type(array_1))
"""
- Nhập module numpy với tên np
- Gọi hàm array của numpy , truyền vào tham số 1 list gồm 3 phần tử 1, 2, 3
- Giá trị trả về của hàm array là một mảng numpy gán cho biến array_1
- In mảng numpy array_1
- In kiểu dữ liệu của mảng numpy array_1
"""
# Noted : np.array chỉ hoạt động với kiểu dữ liệu tuần tự có thứ tụ

[1 2 3]
<class 'numpy.ndarray'>


'\n- Nhập module numpy với tên np\n- Gọi hàm array của numpy , truyền vào tham số 1 list gồm 3 phần tử 1, 2, 3\n- Giá trị trả về của hàm array là một mảng numpy gán cho biến array_1\n- In mảng numpy array_1\n- In kiểu dữ liệu của mảng numpy array_1\n'

In [ ]:
# Từ list, tuple: sử dụng asarray()
import numpy as np
x = [1, 2, 3]
a = np.asarray(x)
print(a)
"""
- Nhập module numpy với tên np
- Tạo 1 list x gồm 3 phần tử 1, 2, 3
- Gọi hàm asarray của numpy , truyềng vào tham số là list x
- Kết quả trả về của hàm asarray là 1 mảng numpy mới, được gán cho biến a
- In a ra màn hình
"""

[1 2 3]


In [ ]:
# Từ range: sử dụng numpy.arange(start, stop, step, dtype)
mang_2 = np.arange(10, 20 ,2)
print(mang_2)
"""
- Gọi hàm arange của numpy, truyền các vào tham số start = 10, stop = 20, step = 2
- Giá trị của hàm là một mảng numpy có giá trị từ 10 đến trước 20, mỗi phần tử cách đều nhau 2 đơn vị gán cho biến mang_2
- In mảng numpy mang_2
"""
# Noted : 
# Điểm yếu của arange: truyền vào tham số là float
# Nguyên nhân : Sai lệch giá trị phần tử do sai số khi tính toán
# Hệ quả : 
# Số lượng phần tử có thể không chính xác như mong đợi
# Không chính xác trong việc kiểm tra sự tồn tại của một phần tử

In [ ]:
# o	Từ range có khoảng cách đều nhau: sử dụng numpy.linspace(start, stop, num, endpoint, dtype)
mang_3 = np.linspace(10, 20, 5)
print(mang_3)
mang_4 = np.linspace(10, 20, 5, endpoint = False)
print(mang_4)
"""
- Gọi hàm linspace của numpy, truyền vào 3 tham số start = 10, stop = 20, step = 5
- Hàm sẽ trả về một mảng numpy chứa các giá trị từ 10 đến 20, mỗi phần tử cách đều nhau 5 đơn vị, gán vào biến mang_3
- Gọi hàm linspace của numpy lần 2, truyền vào 4 tham số start = 10, stop = 20, step = 5, endpoint = False
- Hàm sẽ trả về một mảng numpy chứa các giá trị từ 10 đến trước 20, mỗi phân tử cách đều nhau 5 đơn vị
"""


[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]


In [ ]:
# 4.3.2  Thao tác trên mảng:
# o	Số phần tử của mảng
print(array_1)
print(array_1.shape[0]) #(line, columns, class)
"""
- In ra mảng numpy array_1
- In kích thước chiều đầu tiên của mảng numpy array_1 theo dòng
"""


[1 2 3]
3


'\n- In ra mảng numpy array_1\n- In ra phần tử trong mảng numpy array_1 tại index = 0\n'

In [ ]:
# Cập nhật phần tử trong mảng
array_1[1] = 250
print(array_1[1])
"""
- Gán giá trị 250 cho phần tử trong mảng numpy array_1 có index = 1 
- In ra phần tử trong mảng array_1 có index = 1
"""


In [ ]:
# Truy xuất phần tử trong mảng
mang_4 = np.array([1, 3, 2, 4, 5, 7, 9])
print(mang_4)
print(mang_4[3])
print(mang_4[3:])
print(mang_4[3:5])
print(mang_4[mang_4 < 5])

In [13]:
import pandas as pd
nd_array_1 = np.array(['a', 'b', 'c', 'd', 'e'])
# s2 = pd.Series(nd_array_1, index = [100, 101, 102, 103])
s2 = pd.Series(nd_array_1, [1, 2, 3, 4, 5])
print(s2)
s2.index[[0, 2, 4]]

1    a
2    b
3    c
4    d
5    e
dtype: object


Index([1, 3, 5], dtype='int64')

In [19]:
# Data Frame
lst2 = [['Bibi', 7], ['Xuxu', 5], ['Kent', 10]]
df2 = pd.DataFrame(lst2, columns=['Name', 'Age'])
print(df2)
"""
- Khởi tạo một list tên lst2 gồm 3 phần tử. Mỗi phần tử là 1 list gồm 2 phần tử
- List con thứ nhất gồm 2 phần từ 'Bibi' và 7
- List con thứ hai gồm 2 phần tử 'Xuxu' và 5
- List con thứ ba gồm 2 phần tử 'Kent' và 10
- Gọi hàm DataFrame của pandas , truyền vào 2 tham số: list lst2, và truyền tham số cho index là 1 lst gồm 2 phần tử 'Name' và 'Age'
- Hàm trả về một biến DataFrame có 2 cột, 3 hàng
- 2 Cột 'Name', 'Age'
- Mỗi phần tử trong lst2 tương ứng với 1 hàng
"""
                                  

   Name  Age
0  Bibi    7
1  Xuxu    5
2  Kent   10


"\n- Khởi tạo một list tên lst2 gồm 3 phần tử. Mỗi phần tử là 1 list gồm 2 phần tử\n- List con thứ nhất gồm 2 phần từ 'Bibi' và 7\n- List con thứ hai gồm 2 phần tử 'Xuxu' và 5\n- List con thứ ba gồm 2 phần tử 'Kent' và 10\n- Gọi hàm DataFrame của pandas , truyền vào 2 tham số: list lst2, và truyền tham số cho index là 1 lst gồm 2 phần tử 'Name' và 'Age'\n- Hàm trả về một biến DataFrame có 2 cột, 3 hàng\n- 2 Cột 'Name', 'Age'\n- Mỗi phần tử trong lst2 tương ứng với 1 hàng\n"

In [53]:
try:
    fileptr = open("file.txt", "r")
except IOError:
    print("File not found")
else:
    print("The file opened succesfully")
    fileptr.close()

The file opened succesfully


In [58]:
try:
    x = int(input("Nhập một số: "))
    y = 10 / x
except ValueError:
    print("Bạn phải nhập một số nguyên hợp lệ.")


ZeroDivisionError: division by zero

In [ ]:
try:    	    
	fileptr = open("file2.txt","r")      
	try:    
	    fileptr.write("Hi I am good")   # Ngoại lệ 
	finally:    
	    fileptr.close()    
	    print("file closed")    
except Exception as e:    
	print("Error")  
	print(e)  


file closed
Error
not writable


In [ ]:
d = { 'name': pd.Series(['An', 'Hoa', 'Trung', 'Huy', 'Thanh', 'Dung'], index = [49, 48, 47, 1, 2, 3]),
      'age': pd.Series([15, 22, 36, 27, 55], index = [49, 48, 47 ,1 ,3])
      }
df = pd.DataFrame(d, columns=['name',  'age'])
print('Loc nhun nhan vien co tuoi > 30\n', df.loc[df['age']>30] )
# [df['age']>30] : Trả về index của các phần tử có giá trị > 30 theo cột age
# df.loc : Truy suất các phần tử tương ứng với index được trả về 

Loc nhun nhan vien co tuoi > 30
      name   age
3    Dung  55.0
47  Trung  36.0


In [55]:
df['age'] > 30

1     False
2     False
3      True
47     True
48    False
49    False
Name: age, dtype: bool