In [5]:
import numpy as np

BÀI TẬP:
BT1: 1. Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8], tạo array arr_c
chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b.
2. Từ arr_a và arr_b ở câu 1 => Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a.
3. Cho arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]), hãy tạo arr_f chỉ chứa các phần tử
có giá trị từ 5 đến 10 của arr_e.

In [ ]:
arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,8])

arr_c = np.array([])

for i in arr_b:
    if ( i in arr_a ):
        arr_c = np.append(arr_c, i)

print(arr_c)


arr_d = np.array([])

for i in arr_a:
    if ( not ( i in arr_b ) ):
        arr_d = np.append(arr_d, i)

print(arr_d)


arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])

arr_f = np.extract( (arr_e > 5) & (arr_e < 10), arr_e) 
print(arr_f)

[6 9 8 6]


BT2: Hãy hoàn tất file đính kèm với các yêu cầu sau:
1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.
2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác
0.
4. Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [ ]:
arr_zeros = np.zeros(10)
arr_zeros[4] = 1
print(arr_zeros)

arr_h = np.arange(10,25)
print(arr_h[::-1])

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = np.extract(arr_k != 0, arr_k)
print(arr_l)

arr_l = np.append(arr_l, [10,20])
print(arr_l)

arr_l = np.insert(arr_l, 5, 100)
print(arr_l)

arr_l = np.delete(arr_l, [0, 1, 2])
print(arr_l)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   3   5  10  20]
[  2   1 100   3   5  10  20]


BT3: Hãy hoàn tất file đính kèm với các yêu cầu sau:
1. Tạo array arr có kích thước 3x3 với các giá trị True
2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_1D,
và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.
3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.
4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.
5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.
6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), Kiểm tra
trong array có giá trị rỗng không?
7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.

In [ ]:
#1
print("Ex1")
arr = np.ones([3,3])
print(arr)

#2
print("Ex2")
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape([3,3])
print(arr_2D)

arr_temp = arr_2D[:,2].copy()
arr_2D[:,2] = arr_2D[:,0]
arr_2D[:,0] = arr_temp
print(arr_2D)

#3
print("Ex3")
arr_2D[[0,1],:] = arr_2D[[1,0],:]
print(arr_2D)

#4
print("Ex4")
arr_2D[::-1]
print(arr_2D)

#5
print("Ex5")
arr_2D[:,[0,1,2]] = arr_2D[:,[2,1,0]]
print(arr_2D)

#Ex6
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
np.isnan(arr_2D_null)
arr_temp = arr_2D_null[arr_2D_null == 1]
print(type(arr_temp))


Ex1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ex2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
Ex3
[[5 4 3]
 [2 1 0]
 [8 7 6]]
Ex4
[[5 4 3]
 [2 1 0]
 [8 7 6]]
Ex5
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[1.]


In [ ]:

#Ex6
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])

condition = np.isnan(arr_2D_null)
print(condition)

#Ex7
arr_2D_null[ np.isnan(arr_2D_null) ] = 0
# [ arr_2D_null == np.nan ] = 0    Khong hoat dong 

arr_2D_null = np.nan_to_num( arr_2D_null , nan = 0 )
print(arr_2D_null)

[[False False False]
 [ True False False]
 [False  True False]
 [False False False]]
[[1. 2. 3.]
 [1. 5. 6.]
 [7. 1. 9.]
 [4. 5. 6.]]


BT2: Hãy hoàn tất file đính kèm với các yêu cầu sau:
1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.
2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác
0.
4. Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [36]:
#Ex1
arr_zeros = np.zeros( 10 )
arr_zeros[5] = 1
print(arr_zeros)

#Ex2
arr_h = np.arange( 10, 25 )
print(arr_h)

#Ex3
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[ arr_k !=0 ]
print(arr_l)

#Ex4
value = [10,20]
for i in range(2):   
    arr_l = np.append( arr_l, value[i] )
print(arr_l)

#Ex5
arr_l = np.insert( arr_l, 5, 100 )
print(arr_l)

#Ex6
arr_l = np.delete( arr_l , [0,1,2] )
print(arr_l)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   3   5  10  20]
[  2   1 100   3   5  10  20]
